#!/bin/bash
if [[ $# -eq 1 ]]; then
     session=$1
# Check if the current directory is not $HOME
elif [ "$(pwd)" != "$HOME" ]; then
    # Include current directory in the find command
    session=$(find ~/personal ~/work/projects ~/reload2024 "$(pwd)" -mindepth 1 -maxdepth 1 -type d | fzf)
else
    # Exclude current directory
    session=$(find ~/personal ~/work/projects ~/reload2024 -mindepth 1 -maxdepth 1 -type d | fzf)
fi


session_name=$(basename "$session" | tr . _)

if ! tmux has-session -t "$session_name" 2> /dev/null; then
	#echo NOSESSION
	tmux new-session -s "$session_name" -c "$session" -d
fi

if tmux list-clients 2>/dev/null | grep -q "^"; then
    tmux switch-client -t "$session_name"
else
    echo "No active tmux client found. Attaching to the session instead..."
    tmux attach-session -t "$session_name" || echo "Session '$session_name' does not exist."
fi

# tmux switch-client -t "$session_name"

